accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path("create/", AccountCreateView.as_view(), name="create"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path("detail/<int:pk>/", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", AccountDeleteView.as_view(), name="delete"),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView, ArticleUpdateView

app_name = 'articleapp'

urlpatterns = [

    path('temp/', TempView.as_view(), name='temp'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),

]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProfileUpdateView.as_view(), name='update'),
]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include("articleapp.urls")),

    path('', hello_world)

    ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

accountapp/models.py
from django.db import models

# Create your models here.


class Registration(models.Model):
    email = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import Registration


# Create your views here.


def hello_world(request):
    if request.method == "POST":
        email = request.POST.get('email')

        reg = Registration()
        reg.email = email
        reg.save()

        reg_all = Registration.objects.all()

        return HttpResponseRedirect(reverse("accountapp:hello_world"))

    reg_all = Registration.objects.all()

    temp = "techit"
    return render(request, 'accountapp/hello_world.html',
                  context={"temp": temp,
                           "reg_all": reg_all})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/create.html"


class AccountLoginView(LoginView):
    template_name = "accountapp/login.html"

class AccountLogoutView(LogoutView):
    pass

class AccountDetailView(DetailView):
    model = User
    template_name = "accountapp/detail.html"
    context_object_name = "target_user"


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = "target_user"
    template_name = "accountapp/update.html"

    def get_success_url(self):
        return reverse("accountapp:detail",
                       kwargs={"pk": self.kwargs["pk"]})

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')

class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = "accountapp/delete.html"

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">

    <div class="my-5">
        <h1>
            SignUp
        </h1>
    </div>

    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>

</div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">

    <div class="my-5">
        <h1>
            Quit : {{ target_user.username }}
        </h1>
    </div>

    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-danger rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>

</div>


{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">

    <div class="my-5">
        <div>
            <img src="{{ target_user.profile.image.url }}" alt=""
             style="height: 15rem; width: 15rem; border-radius: 100rem;
                    object-fit: cover;">
        </div>

        {% if target_user.profile %}
        <h1>
            {{ target_user.profile.nickname }}
        </h1>
        {{ target_user.profile.message }}

        {% elif target_user == user %}
        <a href="{% url 'profileapp:create' %}">
            <h1>
                Create Profile
            </h1>
        </a>
        {% else %}
        <h1>
            Unknown
        </h1>
        {% endif %}
    </div>

    <div style="max-width: 900px; margin: auto">

        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}">
            <div class="btn btn-warning rounded-pill px-5 my-5">
                Update
            </div>
            </a>

            {% if target_user.profile %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
            <div class="btn btn-dark rounded-pill px-5 my-5">
                Update
            </div>
            </a>
            {% endif %}

        </div>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-primary rounded-pill px-5 my-5">
            Article create
        </a>
    </div>

</div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}


<div style="text-align: center">

    <h2 style="font-family: 'Roboto', sans-serif;">
        Registration
    </h2>

    <div class="my-4">
        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div class="row g-2" style="max-width: 900px; margin: auto;">
              <div class="col-md">
                <div class="form-floating">
                  <input type="email" name="email" class="form-control" id="floatingInputGrid" placeholder="name@example.com" value="mdo@example.com">
                  <label for="floatingInputGrid">Email address</label>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-warning rounded-pill px-4 my-5">
                Submit
            </button>
        </form>
    </div>
    
    <div>
        {{ temp }}
    </div>

    <div>
        {% for reg in reg_all %}

            <p>
                {{ reg.email }}
            </p>

        {% endfor %}
    </div>

</div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">

    <div class="my-5">
        <h1>
            Login
        </h1>
    </div>

    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>

</div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


<div class="my-5 text-center">

    <div class="my-5">
        <h1>
            Account Info Update
        </h1>
    </div>

    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4"
                    type="submit">
                Submit
            </button>

        </form>
    </div>

</div>


{% endblock %}