accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path("create/", AccountCreateView.as_view(), name="create"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path("detail/<int:pk>/", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", AccountDeleteView.as_view(), name="delete"),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView, ArticleUpdateView

app_name = 'articleapp'

urlpatterns = [

    path('temp/', TempView.as_view(), name='temp'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),

]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include("articleapp.urls")),

    path('', hello_world)

    ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

{% include 'head.html' %}

<body>

{% include 'header.html' %}

<hr>

</hr>

{% block content %}
{% endblock %}

<hr>

</hr>

{% include 'footer.html' %}



</body>
</html>

templates/footer.html
<div style="text-align: center; font-family: 'Roboto', sans-serif;">

    <div class="mt-5">
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        <span>nav4</span>
    </div>
    <div>
        <h4 class="my-4">
            TechIt
        </h4>
    </div>
</div>

templates/head.html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">



<style>
    a {
        color: black;
        text-decoration: none;
    }

    a:hover {
        color: black;
    }
</style>

templates/header.html
<div style="text-align: center;">
    <div>
        <h1 class="my-5" style="font-family: 'Roboto', sans-serif;">
            TechIt
        </h1>
    </div>
    <div class="mb-5">
        <span>
            <a href="{% url 'articleapp:temp' %}">
                temp
            </a>
        </span>
        <span>nav2</span>
        <span>nav3</span>
        {% if user.is_authenticated %}
        <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                MyPage
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>
        {% else %}
        <span>
            <a href="{% url 'accountapp:login' %}">
                LogIn
            </a>
        </span>

        <span>
            <a href="{% url 'accountapp:create' %}">
                SignUp
            </a>
        </span>
        {% endif %}
    </div>
</div>